version: "3.4"

x-common-variables:
  &db-env-vars
    POSTGRES_DB: item
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    PORT_API: 8080
    PORT_DEBUG: 5005

volumes:
  webflux_data:

networks:
  webflux_rede:

services:
  db-compose:
    container_name: db-postgres
    image: postgres:9.5-alpine
    hostname: postgres # postgres hostname
    restart: always
    ports:
      - 5432:5432
    volumes:
      - webflux_data:/var/lib/postgresql/data
    networks:
      - webflux_rede
    environment:
      *db-env-vars

  web-api:
    image: pauloportfolio/web-api
    build:
      context: ./
      dockerfile: ./dev-dockerfile
      args:
        JAR_FILE: target/*.jar
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - webflux_data:/var/lib/postgresql/data
    depends_on:
      - db-compose
    networks:
      - webflux_rede
    environment:
      DB_URL: r2dbc:pool:postgresql://db-compose:${PORT_DB}/${POSTGRES_DB}
#      DB_URL: r2dbc:pool:postgresql://db-compose:${PORT_DB}/postgres
      <<: *db-env-vars
      PROFILE: dev
      DEBUG_OPTIONS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      #JDK>=09: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
      #JDK  08: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xmx1G -Xms128m -XX:MaxMetaspaceSize=128m
